# Generated by Django 5.2.8 on 2025-11-18 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.BigIntegerField(help_text='ID của Product tương ứng trên Shopify', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('max_guests', models.IntegerField(default=1, help_text='Số khách tối đa')),
                ('area', models.IntegerField(default=0, help_text='Diện tích (m²)')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Ngày check-in')),
                ('end_date', models.DateField(help_text='Ngày check-out')),
                ('customer_email', models.EmailField(help_text='Email của khách hàng', max_length=254)),
                ('shopify_order_id', models.BigIntegerField(blank=True, help_text='ID của Order tương ứng trên Shopify', null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.room')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
